#!/usr/bin/env python3
"""Scatter trees across the mountainous slopes of outdoor_city.world.

The trees are placed so that BOTH the UGV (Husky, ~0.67 m wide) and the UAV can
traverse easily: a jittered-grid Poisson sampling keeps a wide minimum gap
between trunks, trees are kept off steep cliffs and out of the low city valley,
and a clearance radius is held around the robot spawn and every existing model.

The script is idempotent: it replaces the block between the FOREST_BEGIN /
FOREST_END markers in the world, so it can be re-run with different parameters.

Usage:
    python3 generate_forest.py [--trees N] [--spacing M] [--seed S] [--dry-run]
"""
import argparse
import math
import random
import re
from pathlib import Path

import numpy as np
from PIL import Image

# --- paths (relative to this file: .../mobile_manipulator/scripts/) ---
PKG = Path(__file__).resolve().parents[1]
WORLD = PKG / "worlds" / "outdoor_city.world"
HEIGHTMAP = (PKG.parents[0] / "gazebo_models_worlds_collection" / "models"
             / "vrc_heightmap_1" / "materials" / "textures" / "heightmap.png")

# --- heightmap geometry (must match <heightmap> in vrc_heightmap_1/model.sdf) ---
SX, SY, SZ = 500.0, 500.0, 118.0      # size x, y, z-scale (m)
PX, PY, PZ = 0.0, 0.0, -15.0          # heightmap origin offset (m)

# --- placement rules ---
ELEV_MIN, ELEV_MAX = 8.0, 78.0        # foothills (8 m, ~50 m from spawn) up to just below the bare peaks
MAX_SLOPE = 0.35                      # ~19 deg; steeper terrain buries trees / is bare cliff
TRUNK_R = 2.5                         # m: trees seat on the HIGHEST ground under the whole canopy
                                      # footprint (~2.5 m radius), so the uphill branches that
                                      # extend out from the trunk are never cut into the slope
SPAWN_XY = (5.0, 5.0)                 # robot spawn; keep a clear staging area around it
SPAWN_CLEAR = 14.0                    # m radius kept tree-free around spawn
MODEL_CLEAR = 8.0                     # m radius kept tree-free around every existing world model
SINK = -0.5                           # m the trunk base sits relative to the surface.
                                      # NEGATIVE = lifted up (raise trees), positive = pushed down.
TREE_MODELS = ["Tree_1", "Tree_2"]

MARK_BEGIN = "<!-- FOREST_BEGIN (generated by generate_forest.py - do not edit by hand) -->"
MARK_END = "<!-- FOREST_END -->"


def load_height():
    img = np.array(Image.open(HEIGHTMAP).convert("L"), dtype=float)
    return img, img.shape[0]


def elevation(img, n, x, y):
    """Bilinear terrain height at world (x, y). flip_y=True: image top row = +Y."""
    fx = (x - PX) / SX + 0.5
    fy = 0.5 - (y - PY) / SY
    j = min(max(fx * (n - 1), 0), n - 1)
    i = min(max(fy * (n - 1), 0), n - 1)
    j0, i0 = int(j), int(i)
    j1, i1 = min(j0 + 1, n - 1), min(i0 + 1, n - 1)
    tj, ti = j - j0, i - i0
    top = img[i0, j0] * (1 - tj) + img[i0, j1] * tj
    bot = img[i1, j0] * (1 - tj) + img[i1, j1] * tj
    return (top * (1 - ti) + bot * ti) / 255.0 * SZ + PZ


def slope(img, n, x, y):
    """Local terrain slope (rise/run) via central differences over ~1 cell."""
    d = SX / (n - 1)
    ez1, ez2 = elevation(img, n, x + d, y), elevation(img, n, x - d, y)
    ey1, ey2 = elevation(img, n, x, y + d), elevation(img, n, x, y - d)
    gx = (ez1 - ez2) / (2 * d)
    gy = (ey1 - ey2) / (2 * d)
    return math.hypot(gx, gy)


def trunk_top_elev(img, n, x, y):
    """Highest terrain within TRUNK_R of (x, y) so the uphill slope never buries
    the trunk base. Samples the centre + a ring of 8 points."""
    best = elevation(img, n, x, y)
    for k in range(8):
        a = k * math.pi / 4
        best = max(best, elevation(img, n, x + TRUNK_R * math.cos(a),
                                        y + TRUNK_R * math.sin(a)))
    return best


def existing_models(world_text):
    """XY of every <include> model already in the world (for clearance)."""
    pts = []
    for m in re.finditer(r"<include>(.*?)</include>", world_text, re.S):
        b = m.group(1)
        if MARK_BEGIN in b:
            continue
        p = re.search(r"<pose>([^<]+)</pose>", b)
        if p:
            xy = p.group(1).split()
            pts.append((float(xy[0]), float(xy[1])))
    return pts


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--trees", type=int, default=130, help="max number of trees")
    ap.add_argument("--spacing", type=float, default=14.0, help="grid spacing (m)")
    ap.add_argument("--jitter", type=float, default=4.0, help="per-tree jitter (m)")
    ap.add_argument("--elev-min", type=float, default=ELEV_MIN, help="lowest terrain elevation to plant on (m)")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--dry-run", action="store_true", help="report only, do not write")
    args = ap.parse_args()
    random.seed(args.seed)
    elev_min = args.elev_min

    img, n = load_height()
    world_text = WORLD.read_text()
    obstacles = existing_models(world_text)

    # Candidate jittered grid over the full terrain, then filter by all rules.
    half = SX / 2 - args.spacing
    candidates = []
    xs = np.arange(-half, half, args.spacing)
    for cx in xs:
        for cy in np.arange(-half, half, args.spacing):
            x = cx + random.uniform(-args.jitter, args.jitter)
            y = cy + random.uniform(-args.jitter, args.jitter)
            e = elevation(img, n, x, y)
            if not (elev_min <= e <= ELEV_MAX):
                continue
            if slope(img, n, x, y) > MAX_SLOPE:
                continue
            if math.hypot(x - SPAWN_XY[0], y - SPAWN_XY[1]) < SPAWN_CLEAR:
                continue
            if any(math.hypot(x - ox, y - oy) < MODEL_CLEAR for ox, oy in obstacles):
                continue
            # seat on the highest ground under the trunk so steep uphill never buries it
            z = trunk_top_elev(img, n, x, y) - SINK
            candidates.append((x, y, z))

    random.shuffle(candidates)
    trees = candidates[: args.trees]

    print(f"terrain {SX:.0f}x{SY:.0f} m, band {elev_min:.0f}-{ELEV_MAX:.0f} m, "
          f"max slope {MAX_SLOPE:.2f}")
    print(f"valid candidates: {len(candidates)}, placing: {len(trees)} trees "
          f"(spacing {args.spacing} m, jitter +/-{args.jitter} m)")
    if trees:
        es = [t[2] for t in trees]
        print(f"tree elevations: {min(es):.0f}..{max(es):.0f} m (mean {sum(es)/len(es):.0f})")
    if args.dry_run:
        return

    # Build the include blocks.
    lines = [MARK_BEGIN]
    for k, (x, y, z) in enumerate(trees):
        model = random.choice(TREE_MODELS)
        yaw = random.uniform(0, 2 * math.pi)
        lines.append(
            f'    <include>\n'
            f'      <uri>model://{model}</uri>\n'
            f'      <name>forest_tree_{k:03d}</name>\n'
            f'      <pose>{x:.2f} {y:.2f} {z:.2f} 0 0 {yaw:.3f}</pose>\n'
            f'    </include>'
        )
    lines.append(f"    {MARK_END}")
    block = "\n".join(lines)

    # Idempotent replace / insert before </world>.
    if MARK_BEGIN in world_text:
        world_text = re.sub(re.escape(MARK_BEGIN) + r".*?" + re.escape(MARK_END),
                            block.strip(), world_text, flags=re.S)
    else:
        world_text = world_text.replace("</world>", block + "\n  </world>")
    WORLD.write_text(world_text)
    print(f"wrote {len(trees)} trees into {WORLD}")


if __name__ == "__main__":
    main()
